name: Flutter CI

on:
  push:
    branches:
      - master

jobs:
  build_apk:
    name: Build Flutter (Android)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-java@v1
        with:
          java-version: '12.x'
      - uses: subosito/flutter-action@v1
        with:
          channel: 'stable' # 'dev', 'alpha', default to: 'stable'
      - run: flutter pub get
      - run: flutter build apk --no-sound-null-safety
      - uses: actions/upload-artifact@v1
        with:
          name: android-build
          path: build/app/outputs/apk/release/app-release.apk
  build_ios:
    name: Build Flutter (iOS)
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-java@v1
        with:
          java-version: '12.x'
      - uses: subosito/flutter-action@v1
        with:
          channel: 'stable'
      - run: flutter pub get
      - run: flutter build ios --release --no-codesign --no-sound-null-safety
      - uses: actions/upload-artifact@v1
        with:
          name: ios-build
          path: build/ios/iphoneos